using System;

namespace ConsoleApp1.Models
{
    public class FullAutoContract
    {
        public string ClientName { get; set; }
        public string DealerPolicyNumber { get; set; }
        public string DealerPolicyNumberSuffix { get; set; }
        public string ProductKey { get; set; }
        public string WarrantyKey { get; set; }
        public string ProducerCode { get; set; }
        public string ProgramName { get; set; }
        public string InsuranceType { get; set; }
        public string CustomerContractNumber { get; set; }
        public string ContractStatus { get; set; }
        public string WarrantySKU { get; set; }
        public string WarrantyDescription { get; set; }
        public string WarrantyType { get; set; }
        public string WarrantySubType { get; set; }
        public string CoverageGroup { get; set; }
        public string ProductType { get; set; }
        public string ProductSubType { get; set; }
        public DateTime? TransactionDate { get; set; }
        public DateTime? ContractPurchaseDate { get; set; }
        public DateTime? RenewalDate { get; set; }
        public DateTime? ProductPurchaseDate { get; set; }
        public DateTime? VehicleInServiceDate { get; set; }
        public int? TermMileage { get; set; }
        public int? TermMonths { get; set; }
        public int? TermHours { get; set; }
        public int? ManufacturerTermMonths { get; set; }
        public string StartOfRiskType { get; set; }
        public DateTime? ManufacturerEffectiveDate { get; set; }
        public DateTime? ManufacturerExpirationDate { get; set; }
        public DateTime? CoverageEffectiveDate { get; set; }
        public DateTime? CoverageExpirationDate { get; set; }
        public int? MileageAtPurchase { get; set; }
        public int? MileageAtCoverageStart { get; set; }
        public int? HoursAtPurchase { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public int? ModelYear { get; set; }
        public string RateClass { get; set; }
        public string New_Used { get; set; }
        public string VIN { get; set; }
        public string CC { get; set; }
        public decimal? ProductPurchasePrice { get; set; }
        public string LoanOrLease { get; set; }
        public decimal? LoanToValue { get; set; }
        public decimal? NADA_MSRPValue { get; set; }
        public decimal? AmountFinanced { get; set; }
        public decimal? LoanAPR { get; set; }
        public string AgreementType { get; set; }
        public string UseType { get; set; }
        public string SalesChannel { get; set; }
        public decimal? ClaimLimitOfLiability { get; set; }
        public decimal? ContractLimitOfLiability { get; set; }
        public int? ClaimCountLimit { get; set; }
        public string DeductibleType { get; set; }
        public decimal? Deductible { get; set; }
        public decimal? DeductibleAtProducer { get; set; }
        public decimal? RetailAmount { get; set; }
        public decimal? AdminAmount { get; set; }
        public decimal? Commission { get; set; }
        public decimal? RemitToAmTrust { get; set; }
        public decimal? InsurancePremium { get; set; }
        public decimal? ReserveAmount { get; set; }
        public decimal? Ceding_Risk_Fee { get; set; }
        public decimal? ContingencyFee { get; set; }
        public decimal? PremiumTax { get; set; }
        public decimal? BaseReserveAmount { get; set; }
        public decimal? SurchargeReserveAmount { get; set; }
        public decimal? SurchargePremium { get; set; }
        public decimal? ServiceFee { get; set; }
        public decimal? BrokerFee { get; set; }
        public decimal? ObligorFee { get; set; }
        public decimal? NCFCManagementFee { get; set; }
        public decimal? RiskPoolFee { get; set; }
        public decimal? FederalExciseTax { get; set; }
        public DateTime? CancellationDate { get; set; }
        public int? CancellationHours { get; set; }
        public int? CancellationMileage { get; set; }
        public decimal? CancellationPercentageDecimal { get; set; }
        public string CancellationReason { get; set; }
        public string Currency { get; set; }
        public string ReInsuranceCompanyCode { get; set; }
        public string ReInsuranceCompanyName { get; set; }
        public string ReinsuranceType { get; set; }
        public string Administrator { get; set; }
        public string InsuranceCompanyName { get; set; }
        public string ObligorCode { get; set; }
        public string ObligorState { get; set; }
        public string ObligorCountry { get; set; }
        public string FormNumber { get; set; }
        public string CompanyNameOfPurchaser { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerAddress2 { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerState { get; set; }
        public string CustomerZip { get; set; }
        public string CustomerCountry { get; set; }
        public decimal? UserDefinedDecimal1 { get; set; }
        public decimal? UserDefinedDecimal2 { get; set; }
        public decimal? UserDefinedDecimal3 { get; set; }
        public string UserDefinedString1 { get; set; }
        public DateTime? UserDefinedDate1 { get; set; }
    }
}
